# 推送配置
push:
  # CDR推送地址
  cdr_url: "http://localhost:8081/callback/v1/record"
  # 呼叫状态推送地址
  status_url: "http://localhost:8081/callback/v1/status"
  # 并发推送的工作协程数量
  workers: 1000

# 账号配置
account:
  id: "TEST_ACCOUNT"
  service_type: 5000

# 重试配置
retry:
  times: 5
  delays: [0, 5, 30, 300, 1800]  # 立即重试、5秒、30秒、5分钟、30分钟

# 推送间隔配置（秒）
interval:
  cdr: 5
  status: 3
  new_call: 10